# Generated by Django 3.2.3 on 2021-05-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('ac_power', models.BooleanField(default=True)),
                ('led_ok', models.BooleanField(default=True)),
                ('temperature', models.IntegerField()),
                ('angle_x', models.IntegerField()),
                ('angle_y', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('battery', models.IntegerField()),
                ('uptime', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Данные девайса',
                'verbose_name_plural': 'Данные девайсов',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avrora.device'),
        ),
    ]
