# Generated by Django 3.2.3 on 2021-05-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0002_auto_20210526_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avrora.device'),
        ),
    ]
