# Generated by Django 3.2.3 on 2021-05-26 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0003_auto_20210526_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='date_upd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
