# Generated by Django 3.2.3 on 2021-05-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0004_devicedata_date_upd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
