# Generated by Django 3.2.3 on 2021-06-11 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0005_alter_devicedata_date_upd'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='device',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='avrora.device'),
        ),
    ]
