# Generated by Django 3.2.3 on 2021-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0006_auto_20210611_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='organization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='telephone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
