# Generated by Django 3.2.3 on 2021-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0008_auto_20210611_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='send_alert',
            field=models.BooleanField(default=False),
        ),
    ]
