# Generated by Django 3.2.3 on 2021-06-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0010_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='organization',
        ),
    ]
