# Generated by Django 3.2.3 on 2021-06-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avrora', '0011_auto_20210627_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='avrora.organization'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='avrora.organization'),
        ),
    ]
